services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - /sys/kernel/mm/transparent_hugepage:/sys/kernel/mm/transparent_hugepage:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      ALLOW_EMPTY_PASSWORD: yes
      CLICKHOUSE_DB: check24
    ports:
      - "8002:9000"
      - "8123:8123"  # Changed HTTP port mapping
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    networks:
      - ch_network
networks:
  ch_network:
    driver: bridge
